# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AntiVirus.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AntiVirus(object):
    def setupUi(self, AntiVirus):
        AntiVirus.setObjectName("AntiVirus")
        AntiVirus.resize(1000, 618)
        AntiVirus.setStyleSheet("QWidget#AntiVirus\n"
                                "{\n"
                                "    background-color:white\n"
                                "}")
        self.tabWidget = QtWidgets.QTabWidget(AntiVirus)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 618))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabWidget.setObjectName("tabWidget")

        self.retranslateUi(AntiVirus)
        QtCore.QMetaObject.connectSlotsByName(AntiVirus)

    def retranslateUi(self, AntiVirus):
        _translate = QtCore.QCoreApplication.translate
        AntiVirus.setWindowTitle(_translate("AntiVirus", "AntiVirus"))
