# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GetVirus.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GetVirus(object):
    def setupUi(self, GetVirus):
        GetVirus.setObjectName("GetVirus")
        GetVirus.resize(1000, 618)
        GetVirus.setStyleSheet("QWidget#GetVirus\n"
                               "{\n"
                               "    background-color:white\n"
                               "}")
        self.progressBar = QtWidgets.QProgressBar(GetVirus)
        self.progressBar.setGeometry(QtCore.QRect(128, 0, 872, 32))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar2 = QtWidgets.QProgressBar(GetVirus)
        self.progressBar2.setGeometry(QtCore.QRect(128, 32, 872, 32))
        self.progressBar2.setMaximum(0)
        self.progressBar2.setProperty("value", 0)
        self.progressBar2.setObjectName("progressBar2")
        self.pushButton_start = QtWidgets.QPushButton(GetVirus)
        self.pushButton_start.setGeometry(QtCore.QRect(0, 0, 128, 64))
        self.pushButton_start.setStyleSheet("QPushButton#pushButton_start\n"
                                            "{\n"
                                            "    border:0px solid rgb(16,124,16);\n"
                                            "    background-color:white\n"
                                            "}\n"
                                            "QPushButton#pushButton_start:hover\n"
                                            "{\n"
                                            "    border:2px solid rgb(16,124,16);\n"
                                            "    border-color:green\n"
                                            "}\n"
                                            "QPushButton#pushButton_start:pressed\n"
                                            "{\n"
                                            "    background-color:rgb(195, 195, 195)\n"
                                            "}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.textEdit_output = QtWidgets.QTextEdit(GetVirus)
        self.textEdit_output.setGeometry(QtCore.QRect(0, 64, 1000, 554))
        self.textEdit_output.setStyleSheet("QTextEdit#textEdit_output\n"
                                           "{\n"
                                           "    border:none\n"
                                           "}")
        self.textEdit_output.setReadOnly(True)
        self.textEdit_output.setObjectName("textEdit_output")

        self.retranslateUi(GetVirus)
        QtCore.QMetaObject.connectSlotsByName(GetVirus)

    def retranslateUi(self, GetVirus):
        _translate = QtCore.QCoreApplication.translate
        GetVirus.setWindowTitle(_translate("GetVirus", "GetVirus"))
        self.progressBar.setFormat(_translate("GetVirus", "%v/%m"))
        self.progressBar2.setFormat(_translate("GetVirus", "%v/%m"))
        self.pushButton_start.setText(_translate("GetVirus", "开始"))
