# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Virus.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Virus(object):
    def setupUi(self, Virus):
        Virus.setObjectName("Virus")
        Virus.resize(1000, 618)
        Virus.setStyleSheet("QWidget#AntiVirus\n"
                            "{\n"
                            "    background-color:white\n"
                            "}")
        self.pushButton_start = QtWidgets.QPushButton(Virus)
        self.pushButton_start.setEnabled(True)
        self.pushButton_start.setGeometry(QtCore.QRect(0, 0, 128, 64))
        self.pushButton_start.setStyleSheet("QPushButton#pushButton_start\n"
                                            "{\n"
                                            "    border:0px solid rgb(16,124,16);\n"
                                            "    background-color:white\n"
                                            "}\n"
                                            "QPushButton#pushButton_start:hover\n"
                                            "{\n"
                                            "    border:2px solid rgb(16,124,16);\n"
                                            "    border-color:green\n"
                                            "}\n"
                                            "QPushButton#pushButton_start:pressed\n"
                                            "{\n"
                                            "    background-color:rgb(195, 195, 195)\n"
                                            "}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_filepath = QtWidgets.QLabel(Virus)
        self.label_filepath.setGeometry(QtCore.QRect(128, 0, 872, 32))
        self.label_filepath.setText("")
        self.label_filepath.setObjectName("label_filepath")
        self.progressBar = QtWidgets.QProgressBar(Virus)
        self.progressBar.setGeometry(QtCore.QRect(128, 32, 872, 32))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.listWidget_program = QtWidgets.QListWidget(Virus)
        self.listWidget_program.setGeometry(QtCore.QRect(0, 96, 1000, 522))
        self.listWidget_program.setStyleSheet("QListWidget#listWidget_program\n"
                                              "{\n"
                                              "    border:none\n"
                                              "}")
        self.listWidget_program.setObjectName("listWidget_program")
        self.lineEdit_way = QtWidgets.QLineEdit(Virus)
        self.lineEdit_way.setGeometry(QtCore.QRect(0, 64, 936, 32))
        self.lineEdit_way.setObjectName("lineEdit_way")
        self.pushButton_choose = QtWidgets.QPushButton(Virus)
        self.pushButton_choose.setGeometry(QtCore.QRect(936, 64, 64, 32))
        self.pushButton_choose.setStyleSheet("QPushButton#pushButton_choose\n"
                                             "{\n"
                                             "    border:0px solid rgb(16,124,16);\n"
                                             "    background-color:white\n"
                                             "}\n"
                                             "QPushButton#pushButton_choose:hover\n"
                                             "{\n"
                                             "    border:2px solid rgb(16,124,16);\n"
                                             "    border-color:green\n"
                                             "}\n"
                                             "QPushButton#pushButton_choose:pressed\n"
                                             "{\n"
                                             "    background-color:rgb(195, 195, 195)\n"
                                             "}")
        self.pushButton_choose.setObjectName("pushButton_choose")

        self.retranslateUi(Virus)
        QtCore.QMetaObject.connectSlotsByName(Virus)

    def retranslateUi(self, Virus):
        _translate = QtCore.QCoreApplication.translate
        Virus.setWindowTitle(_translate("Virus", "Virus"))
        self.pushButton_start.setText(_translate("Virus", "开始"))
        self.progressBar.setFormat(_translate("Virus", "%p%"))
        self.lineEdit_way.setText(_translate("Virus", "C:\\"))
        self.lineEdit_way.setPlaceholderText(_translate("Virus", "请输入扫描路径"))
        self.pushButton_choose.setText(_translate("Virus", "..."))
