# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComputerHousekeeper.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComputerHousekeeper(object):
    def setupUi(self, ComputerHousekeeper):
        ComputerHousekeeper.setObjectName("ComputerHousekeeper")
        ComputerHousekeeper.resize(1000, 618)
        ComputerHousekeeper.setStyleSheet("QWidget#ComputerHousekeeper1_0\n"
                                          "{\n"
                                          "    background-color:white\n"
                                          "}")
        self.centralwidget = QtWidgets.QWidget(ComputerHousekeeper)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_panel = QtWidgets.QFrame(self.centralwidget)
        self.frame_panel.setGeometry(QtCore.QRect(0, 0, 64, 618))
        self.frame_panel.setStyleSheet("QFrame#frame_panel\n"
                                       "{\n"
                                       "    background-color:white\n"
                                       "}")
        self.frame_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_panel.setObjectName("frame_panel")
        self.pushButton_task = QtWidgets.QPushButton(self.frame_panel)
        self.pushButton_task.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.pushButton_task.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pushButton_task.setStyleSheet("QPushButton#pushButton_task\n"
                                           "{\n"
                                           "    border:0px solid rgb(16,124,16);\n"
                                           "    background-color:white\n"
                                           "}\n"
                                           "QPushButton#pushButton_task:hover\n"
                                           "{\n"
                                           "    border:2px solid rgb(16,124,16);\n"
                                           "    border-color:green\n"
                                           "}\n"
                                           "QPushButton#pushButton_task:pressed\n"
                                           "{\n"
                                           "    background-color:rgb(195, 195, 195)\n"
                                           "}")
        self.pushButton_task.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_task.setObjectName("pushButton_task")
        self.pushButton_tool = QtWidgets.QPushButton(self.frame_panel)
        self.pushButton_tool.setGeometry(QtCore.QRect(0, 64, 64, 64))
        self.pushButton_tool.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pushButton_tool.setStyleSheet("QPushButton#pushButton_tool\n"
                                           "{\n"
                                           "    border:0px solid rgb(16,124,16);\n"
                                           "    background-color:white\n"
                                           "}\n"
                                           "QPushButton#pushButton_tool:hover\n"
                                           "{\n"
                                           "    border:2px solid rgb(16,124,16);\n"
                                           "    border-color:green\n"
                                           "}\n"
                                           "QPushButton#pushButton_tool:pressed\n"
                                           "{\n"
                                           "    background-color:rgb(195, 195, 195)\n"
                                           "}")
        self.pushButton_tool.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_tool.setObjectName("pushButton_tool")
        self.pushButton_more = QtWidgets.QPushButton(self.frame_panel)
        self.pushButton_more.setGeometry(QtCore.QRect(0, 128, 64, 64))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_more.setFont(font)
        self.pushButton_more.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pushButton_more.setStyleSheet("QPushButton#pushButton_more\n"
                                           "{\n"
                                           "    border:0px solid rgb(16,124,16);\n"
                                           "    background-color:white\n"
                                           "}\n"
                                           "QPushButton#pushButton_more:hover\n"
                                           "{\n"
                                           "    border:2px solid rgb(16,124,16);\n"
                                           "    border-color:green\n"
                                           "}\n"
                                           "QPushButton#pushButton_more:pressed\n"
                                           "{\n"
                                           "    background-color:rgb(195, 195, 195)\n"
                                           "}")
        self.pushButton_more.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_more.setCheckable(False)
        self.pushButton_more.setAutoRepeat(False)
        self.pushButton_more.setAutoExclusive(False)
        self.pushButton_more.setAutoDefault(False)
        self.pushButton_more.setDefault(False)
        self.pushButton_more.setFlat(False)
        self.pushButton_more.setObjectName("pushButton_more")
        self.frame_ui = QtWidgets.QFrame(self.centralwidget)
        self.frame_ui.setGeometry(QtCore.QRect(64, 0, 934, 618))
        self.frame_ui.setStyleSheet("QFrame#frame_ui\n"
                                    "{\n"
                                    "    background-color:white\n"
                                    "}")
        self.frame_ui.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ui.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ui.setObjectName("frame_ui")
        ComputerHousekeeper.setCentralWidget(self.centralwidget)

        self.retranslateUi(ComputerHousekeeper)
        QtCore.QMetaObject.connectSlotsByName(ComputerHousekeeper)

    def retranslateUi(self, ComputerHousekeeper):
        _translate = QtCore.QCoreApplication.translate
        ComputerHousekeeper.setWindowTitle(_translate("ComputerHousekeeper", "ComputerHousekeeper"))
        self.pushButton_task.setText(_translate("ComputerHousekeeper", "任务"))
        self.pushButton_tool.setText(_translate("ComputerHousekeeper", "工具"))
        self.pushButton_more.setText(_translate("ComputerHousekeeper", "更多"))
