# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task(object):
    def setupUi(self, Task):
        Task.setObjectName("Task")
        Task.resize(1000, 618)
        Task.setStyleSheet("QWidget#Task\n"
                           "{\n"
                           "    background-color:white\n"
                           "}")
        self.listWidget_name = QtWidgets.QListWidget(Task)
        self.listWidget_name.setGeometry(QtCore.QRect(0, 0, 128, 618))
        self.listWidget_name.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget_name.setStyleSheet("QListWidget#listWidget_name\n"
                                           "{\n"
                                           "    border:none\n"
                                           "}")
        self.listWidget_name.setObjectName("listWidget_name")
        self.frame_content = QtWidgets.QFrame(Task)
        self.frame_content.setGeometry(QtCore.QRect(128, 0, 872, 618))
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")

        self.retranslateUi(Task)
        QtCore.QMetaObject.connectSlotsByName(Task)

    def retranslateUi(self, Task):
        _translate = QtCore.QCoreApplication.translate
        Task.setWindowTitle(_translate("Task", "Task"))
