# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tool(object):
    def setupUi(self, Tool):
        Tool.setObjectName("Tool")
        Tool.resize(1000, 618)
        Tool.setStyleSheet("QWidget#Tool\n"
                           "{\n"
                           "    background-color:white\n"
                           "}")
        self.listWidget_tool = QtWidgets.QListWidget(Tool)
        self.listWidget_tool.setGeometry(QtCore.QRect(0, 0, 1000, 618))
        self.listWidget_tool.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget_tool.setStyleSheet("QListWidget#listWidget_tool\n"
                                           "{\n"
                                           "    border:none\n"
                                           "}")
        self.listWidget_tool.setObjectName("listWidget_tool")

        self.retranslateUi(Tool)
        QtCore.QMetaObject.connectSlotsByName(Tool)

    def retranslateUi(self, Tool):
        _translate = QtCore.QCoreApplication.translate
        Tool.setWindowTitle(_translate("Tool", "Tool"))
