# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Memory.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Memory(object):
    def setupUi(self, Memory):
        Memory.setObjectName("Memory")
        Memory.resize(1000, 618)
        Memory.setStyleSheet("QWidget#Memory\n"
                             "{\n"
                             "    background-color:white\n"
                             "}")

        self.retranslateUi(Memory)
        QtCore.QMetaObject.connectSlotsByName(Memory)

    def retranslateUi(self, Memory):
        _translate = QtCore.QCoreApplication.translate
        Memory.setWindowTitle(_translate("Memory", "Memory"))
