# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Performance.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Performance(object):
    def setupUi(self, Performance):
        Performance.setObjectName("Performance")
        Performance.resize(1000, 618)
        Performance.setStyleSheet("QWidget#Performance\n"
                                  "{\n"
                                  "    background-color:white\n"
                                  "}")
        self.listWidget_name = QtWidgets.QListWidget(Performance)
        self.listWidget_name.setGeometry(QtCore.QRect(0, 0, 128, 618))
        self.listWidget_name.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget_name.setStyleSheet("QListWidget#listWidget_name\n"
                                           "{\n"
                                           "    border:none\n"
                                           "}")
        self.listWidget_name.setObjectName("listWidget_name")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_name.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_name.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_name.addItem(item)
        self.frame_content = QtWidgets.QFrame(Performance)
        self.frame_content.setGeometry(QtCore.QRect(128, 0, 872, 618))
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")

        self.retranslateUi(Performance)
        QtCore.QMetaObject.connectSlotsByName(Performance)

    def retranslateUi(self, Performance):
        _translate = QtCore.QCoreApplication.translate
        Performance.setWindowTitle(_translate("Performance", "Performance"))
        __sortingEnabled = self.listWidget_name.isSortingEnabled()
        self.listWidget_name.setSortingEnabled(False)
        item = self.listWidget_name.item(0)
        item.setText(_translate("Performance", "CPU"))
        item = self.listWidget_name.item(1)
        item.setText(_translate("Performance", "内存"))
        item = self.listWidget_name.item(2)
        item.setText(_translate("Performance", "WLAN"))
        self.listWidget_name.setSortingEnabled(__sortingEnabled)
