# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskManager(object):
    def setupUi(self, TaskManager):
        TaskManager.setObjectName("TaskManager")
        TaskManager.resize(1000, 618)
        TaskManager.setStyleSheet("QWidget#TaskManager\n"
                                  "{\n"
                                  "    background-color:white\n"
                                  "}")
        self.tabWidget = QtWidgets.QTabWidget(TaskManager)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 618))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabWidget.setStyleSheet("QTabWidget#tabWidget\n"
                                     "{\n"
                                     "    border:none\n"
                                     "}")
        self.tabWidget.setObjectName("tabWidget")

        self.retranslateUi(TaskManager)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(TaskManager)

    def retranslateUi(self, TaskManager):
        _translate = QtCore.QCoreApplication.translate
        TaskManager.setWindowTitle(_translate("TaskManager", "TaskManager"))
