# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GarbageCleaning.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GarbageCleaning(object):
    def setupUi(self, GarbageCleaning):
        GarbageCleaning.setObjectName("GarbageCleaning")
        GarbageCleaning.resize(1000, 618)
        GarbageCleaning.setStyleSheet("QWidget#GarbageCleaning\n"
                                      "{\n"
                                      "    background-color:white\n"
                                      "}")
        self.lineEdit_path = QtWidgets.QLineEdit(GarbageCleaning)
        self.lineEdit_path.setGeometry(QtCore.QRect(0, 0, 808, 32))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.pushButton_start = QtWidgets.QPushButton(GarbageCleaning)
        self.pushButton_start.setGeometry(QtCore.QRect(872, 0, 64, 32))
        self.pushButton_start.setStyleSheet("QPushButton#pushButton_start\n"
                                            "{\n"
                                            "    border:0px solid rgb(16,124,16);\n"
                                            "    background-color:white\n"
                                            "}\n"
                                            "QPushButton#pushButton_start:hover\n"
                                            "{\n"
                                            "    border:2px solid rgb(16,124,16);\n"
                                            "    border-color:green\n"
                                            "}\n"
                                            "QPushButton#pushButton_start:pressed\n"
                                            "{\n"
                                            "    background-color:rgb(195, 195, 195)\n"
                                            "}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_del = QtWidgets.QPushButton(GarbageCleaning)
        self.pushButton_del.setGeometry(QtCore.QRect(936, 0, 64, 32))
        self.pushButton_del.setStyleSheet("QPushButton#pushButton_del\n"
                                          "{\n"
                                          "    border:0px solid rgb(16,124,16);\n"
                                          "    background-color:white\n"
                                          "}\n"
                                          "QPushButton#pushButton_del:hover\n"
                                          "{\n"
                                          "    border:2px solid rgb(16,124,16);\n"
                                          "    border-color:green\n"
                                          "}\n"
                                          "QPushButton#pushButton_del:pressed\n"
                                          "{\n"
                                          "    background-color:rgb(195, 195, 195)\n"
                                          "}")
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_choose = QtWidgets.QPushButton(GarbageCleaning)
        self.pushButton_choose.setGeometry(QtCore.QRect(808, 0, 64, 32))
        self.pushButton_choose.setStyleSheet("QPushButton#pushButton_choose\n"
                                             "{\n"
                                             "    border:0px solid rgb(16,124,16);\n"
                                             "    background-color:white\n"
                                             "}\n"
                                             "QPushButton#pushButton_choose:hover\n"
                                             "{\n"
                                             "    border:2px solid rgb(16,124,16);\n"
                                             "    border-color:green\n"
                                             "}\n"
                                             "QPushButton#pushButton_choose:pressed\n"
                                             "{\n"
                                             "    background-color:rgb(195, 195, 195)\n"
                                             "}")
        self.pushButton_choose.setObjectName("pushButton_choose")
        self.listWidget_result = QtWidgets.QListWidget(GarbageCleaning)
        self.listWidget_result.setGeometry(QtCore.QRect(0, 32, 1000, 586))
        self.listWidget_result.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget_result.setStyleSheet("QListWidget#listWidget_result\n"
                                             "{\n"
                                             "    border:none\n"
                                             "}")
        self.listWidget_result.setObjectName("listWidget_result")

        self.retranslateUi(GarbageCleaning)
        QtCore.QMetaObject.connectSlotsByName(GarbageCleaning)

    def retranslateUi(self, GarbageCleaning):
        _translate = QtCore.QCoreApplication.translate
        GarbageCleaning.setWindowTitle(_translate("GarbageCleaning", "GarbageCleaning"))
        self.lineEdit_path.setPlaceholderText(_translate("GarbageCleaning", "请输入路径"))
        self.pushButton_start.setText(_translate("GarbageCleaning", "开始"))
        self.pushButton_del.setText(_translate("GarbageCleaning", "清除"))
        self.pushButton_choose.setText(_translate("GarbageCleaning", "选择"))
