# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Process.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Process(object):
    def setupUi(self, Process):
        Process.setObjectName("Process")
        Process.resize(1000, 618)
        Process.setStyleSheet("QWidget#Process\n"
                              "{\n"
                              "    background-color:white\n"
                              "}")
        self.treeView = QtWidgets.QTreeView(Process)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 1000, 586))
        self.treeView.setStyleSheet("QTreeView#treeView\n"
                                    "{\n"
                                    "    border:none\n"
                                    "}")
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setItemsExpandable(True)
        self.treeView.setExpandsOnDoubleClick(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.pushButton_refresh = QtWidgets.QPushButton(Process)
        self.pushButton_refresh.setGeometry(QtCore.QRect(936, 586, 64, 32))
        self.pushButton_refresh.setStyleSheet("QPushButton#pushButton_refresh\n"
                                              "{\n"
                                              "    border:0px solid rgb(16,124,16);\n"
                                              "    background-color:white\n"
                                              "}\n"
                                              "QPushButton#pushButton_refresh:hover\n"
                                              "{\n"
                                              "    border:2px solid rgb(16,124,16);\n"
                                              "    border-color:green\n"
                                              "}\n"
                                              "QPushButton#pushButton_refresh:pressed\n"
                                              "{\n"
                                              "    background-color:rgb(195, 195, 195)\n"
                                              "}")
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.pushButton_stop = QtWidgets.QPushButton(Process)
        self.pushButton_stop.setGeometry(QtCore.QRect(872, 586, 64, 32))
        self.pushButton_stop.setStyleSheet("QPushButton#pushButton_stop\n"
                                           "{\n"
                                           "    border:0px solid rgb(16,124,16);\n"
                                           "    background-color:white\n"
                                           "}\n"
                                           "QPushButton#pushButton_stop:hover\n"
                                           "{\n"
                                           "    border:2px solid rgb(16,124,16);\n"
                                           "    border-color:green\n"
                                           "}\n"
                                           "QPushButton#pushButton_stop:pressed\n"
                                           "{\n"
                                           "    background-color:rgb(195, 195, 195)\n"
                                           "}")
        self.pushButton_stop.setObjectName("pushButton_stop")

        self.retranslateUi(Process)
        QtCore.QMetaObject.connectSlotsByName(Process)

    def retranslateUi(self, Process):
        _translate = QtCore.QCoreApplication.translate
        Process.setWindowTitle(_translate("Process", "Process"))
        self.pushButton_refresh.setText(_translate("Process", "刷新"))
        self.pushButton_stop.setText(_translate("Process", "结束"))
