# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartItem(object):
    def setupUi(self, StartItem):
        StartItem.setObjectName("StartItem")
        StartItem.resize(1000, 618)
        StartItem.setStyleSheet("QWidget#StartItem\n"
                                "{\n"
                                "    background-color:white\n"
                                "}")
        self.treeView = QtWidgets.QTreeView(StartItem)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 1000, 618))
        self.treeView.setStyleSheet("QTreeView#treeView\n"
                                    "{\n"
                                    "    border:none\n"
                                    "}")
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)

        self.retranslateUi(StartItem)
        QtCore.QMetaObject.connectSlotsByName(StartItem)

    def retranslateUi(self, StartItem):
        _translate = QtCore.QCoreApplication.translate
        StartItem.setWindowTitle(_translate("StartItem", "StartItem"))
