# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WLAN.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WLAN(object):
    def setupUi(self, WLAN):
        WLAN.setObjectName("WLAN")
        WLAN.resize(1000, 618)
        WLAN.setStyleSheet("QWidget#WLAN\n"
                           "{\n"
                           "    background-color:white\n"
                           "}")

        self.retranslateUi(WLAN)
        QtCore.QMetaObject.connectSlotsByName(WLAN)

    def retranslateUi(self, WLAN):
        _translate = QtCore.QCoreApplication.translate
        WLAN.setWindowTitle(_translate("WLAN", "WLAN"))
