# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'More.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_More(object):
    def setupUi(self, More):
        More.setObjectName("More")
        More.resize(1000, 618)
        More.setStyleSheet("QWidget#More\n"
                           "{\n"
                           "    background-color:white\n"
                           "}")
        self.frame_name = QtWidgets.QFrame(More)
        self.frame_name.setGeometry(QtCore.QRect(0, 0, 128, 618))
        self.frame_name.setStyleSheet("QFrame#frame_name\n"
                                      "{\n"
                                      "    background-color:white\n"
                                      "}")
        self.frame_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_name.setObjectName("frame_name")
        self.pushButton_about = QtWidgets.QPushButton(self.frame_name)
        self.pushButton_about.setGeometry(QtCore.QRect(0, 0, 128, 32))
        self.pushButton_about.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pushButton_about.setStyleSheet("QPushButton#pushButton_about\n"
                                            "{\n"
                                            "    border:0px solid rgb(16,124,16);\n"
                                            "    background-color:white\n"
                                            "}\n"
                                            "QPushButton#pushButton_about:hover\n"
                                            "{\n"
                                            "    border:2px solid rgb(16,124,16);\n"
                                            "    border-color:green\n"
                                            "}\n"
                                            "QPushButton#pushButton_about:pressed\n"
                                            "{\n"
                                            "    background-color:rgb(195, 195, 195)\n"
                                            "}")
        self.pushButton_about.setObjectName("pushButton_about")
        self.frame_content = QtWidgets.QFrame(More)
        self.frame_content.setGeometry(QtCore.QRect(128, 0, 872, 618))
        self.frame_content.setStyleSheet("QFrame#frame_content\n"
                                         "{\n"
                                         "    background-color:white\n"
                                         "}")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")

        self.retranslateUi(More)
        QtCore.QMetaObject.connectSlotsByName(More)

    def retranslateUi(self, More):
        _translate = QtCore.QCoreApplication.translate
        More.setWindowTitle(_translate("More", "More"))
        self.pushButton_about.setText(_translate("More", "关于"))
